---
name: Data-Token
version: v0.0.4
author:
  - 'Scott Penrose <scott@cpan.org>'
abstract: Generate an unpredictable unique token
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Data::UUID: 0
  Digest::SHA: 0
  Test::More: 0
  version: 0
provides:
  Data::Token:
    file: lib/Data/Token.pm
    version: v0.0.4
generated_by: Module::Build version 0.2806
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
